export const ticketModel = {
  entity: "tickets",
  primaryKey: "id",
  fields: [
    "id",
    "folio",
    "title",
    "description",
    "ticket_status_id",
    "ticket_priority_id",
    "ticket_category_id",
    "requester_name",
    "requester_email",
    "requester_area",
    "assignee_user_id",
    "created_by",
    "due_at",
    "resolved_at",
    "created_at",
    "updated_at",
  ],
  relations: [
    "ticket_statuses",
    "ticket_priorities",
    "ticket_categories",
    "users",
    "ticket_events",
    "audit_logs",
  ],
};
