export const AUDIT_LOG_BLUEPRINT = {
  entity: "audit_logs",
  fields: [
    "id",
    "operator_id",
    "operator_role",
    "module_name",
    "action_key",
    "entity_name",
    "entity_id",
    "before_snapshot",
    "after_snapshot",
    "metadata",
    "ip_address",
    "user_agent",
    "created_at",
  ],
  requiredFields: ["module_name", "action_key", "entity_name", "created_at"],
};

export const AUDIT_ACTIONS = [
  "auth.login",
  "auth.refresh",
  "auth.logout",
  "users.view",
  "users.update",
  "tickets.view",
  "tickets.create",
  "tickets.update",
  "tickets.assign",
  "inventory.view",
  "inventory.create",
  "inventory.update",
  "inventory.assign",
  "telephony.view",
  "telephony.create",
  "telephony.update",
  "services.view",
  "services.create",
  "services.update",
  "access.create",
  "access.update",
  "access.view_sensitive",
  "infrastructure.create",
  "infrastructure.update",
  "infrastructure.view",
];
