export const RBAC_SEED = {
  roles: [
    {
      key: "admin_systems",
      label: "Admin",
      description: "Acceso total a configuración, catálogos y operaciones.",
    },
    {
      key: "operator",
      label: "Operador",
      description: "Operación diaria sobre tickets, inventario, servicios y telefonía.",
    },
    {
      key: "requester",
      label: "Solicitante",
      description: "Registro y seguimiento limitado de solicitudes propias.",
    },
    {
      key: "viewer",
      label: "Consultante",
      description: "Visualización de tableros y lectura limitada.",
    },
  ],
  permissions: [
    "dashboard.view",
    "tickets.view",
    "tickets.create",
    "tickets.update",
    "tickets.assign",
    "inventory.view",
    "inventory.create",
    "inventory.update",
    "inventory.assign",
    "telephony.view",
    "telephony.create",
    "telephony.update",
    "services.view",
    "services.create",
    "services.update",
    "access.create",
    "access.update",
    "access.view_sensitive",
    "infrastructure.create",
    "infrastructure.update",
    "infrastructure.view",
    "users.view",
    "users.create",
    "users.update",
    "users.delete",
    "audit.view",
  ],
  matrix: {
    admin_systems: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "tickets.update",
      "tickets.assign",
      "inventory.view",
      "inventory.create",
      "inventory.update",
      "inventory.assign",
      "telephony.view",
      "telephony.create",
      "telephony.update",
      "services.view",
      "services.create",
      "services.update",
      "access.create",
      "access.update",
      "access.view_sensitive",
      "infrastructure.create",
      "infrastructure.update",
      "infrastructure.view",
      "users.view",
      "users.create",
      "users.update",
      "users.delete",
      "audit.view",
    ],
    operator: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "tickets.update",
      "tickets.assign",
      "inventory.view",
      "inventory.create",
      "inventory.update",
      "inventory.assign",
      "telephony.view",
      "telephony.create",
      "telephony.update",
      "services.view",
      "services.create",
      "services.update",
      "infrastructure.create",
      "infrastructure.update",
      "infrastructure.view",
      "users.view",
      "audit.view",
    ],
    requester: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "services.view",
    ],
    viewer: [
      "dashboard.view",
      "tickets.view",
      "inventory.view",
      "telephony.view",
      "services.view",
      "infrastructure.view",
    ],
  },
};
