export const RBAC_SEED = {
  roles: [
    {
      key: "admin",
      label: "Administrador",
      description: "Acceso total a configuración, catálogos y operaciones.",
    },
    {
      key: "manager",
      label: "Responsable",
      description: "Gestión operativa del equipo y aprobaciones base.",
    },
    {
      key: "agent",
      label: "Analista",
      description: "Operación diaria sobre tickets, activos y servicios.",
    },
    {
      key: "viewer",
      label: "Consulta",
      description: "Visualización de tableros y lectura limitada.",
    },
  ],
  permissions: [
    "dashboard.read",
    "tickets.read",
    "tickets.write",
    "inventory.read",
    "inventory.write",
    "telephony.read",
    "telephony.write",
    "services.read",
    "services.write",
    "users.read",
    "users.write",
    "audit.read",
    "auth.manage",
  ],
  matrix: {
    admin: [
      "dashboard.read",
      "tickets.read",
      "tickets.write",
      "inventory.read",
      "inventory.write",
      "telephony.read",
      "telephony.write",
      "services.read",
      "services.write",
      "users.read",
      "users.write",
      "audit.read",
      "auth.manage",
    ],
    manager: [
      "dashboard.read",
      "tickets.read",
      "tickets.write",
      "inventory.read",
      "telephony.read",
      "services.read",
      "users.read",
      "audit.read",
    ],
    agent: [
      "dashboard.read",
      "tickets.read",
      "tickets.write",
      "inventory.read",
      "inventory.write",
      "telephony.read",
      "services.read",
    ],
    viewer: [
      "dashboard.read",
      "tickets.read",
      "inventory.read",
      "telephony.read",
      "services.read",
    ],
  },
};
