export const RBAC_SEED = {
  roles: [
    {
      key: "admin_systems",
      label: "Administrador de Systems",
      description: "Acceso total a configuración, catálogos y operaciones.",
    },
    {
      key: "operator",
      label: "Operador",
      description: "Operación diaria sobre tickets, activos, servicios y telefonía.",
    },
    {
      key: "requester",
      label: "Solicitante",
      description: "Registro y seguimiento limitado de solicitudes propias.",
    },
    {
      key: "viewer",
      label: "Consulta",
      description: "Visualización de tableros y lectura limitada.",
    },
  ],
  permissions: [
    "dashboard.view",
    "tickets.view",
    "tickets.create",
    "tickets.update",
    "tickets.assign",
    "assets.view",
    "assets.create",
    "assets.update",
    "assets.assign",
    "telephony.view",
    "telephony.create",
    "telephony.update",
    "services.view",
    "services.create",
    "services.update",
    "users.view",
    "users.create",
    "users.update",
    "users.delete",
    "audit.view",
    "accounts.view_sensitive",
  ],
  matrix: {
    admin_systems: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "tickets.update",
      "tickets.assign",
      "assets.view",
      "assets.create",
      "assets.update",
      "assets.assign",
      "telephony.view",
      "telephony.create",
      "telephony.update",
      "services.view",
      "services.create",
      "services.update",
      "users.view",
      "users.create",
      "users.update",
      "users.delete",
      "audit.view",
      "accounts.view_sensitive",
    ],
    operator: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "tickets.update",
      "tickets.assign",
      "assets.view",
      "assets.create",
      "assets.update",
      "assets.assign",
      "telephony.view",
      "telephony.create",
      "telephony.update",
      "services.view",
      "services.create",
      "services.update",
      "users.view",
      "audit.view",
    ],
    requester: [
      "dashboard.view",
      "tickets.view",
      "tickets.create",
      "services.view",
    ],
    viewer: [
      "dashboard.view",
      "tickets.view",
      "assets.view",
      "telephony.view",
      "services.view",
    ],
  },
};
